version: '3.8'
services:
  stats-server:
    build: ./statistics
    container_name: statistics-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics-server
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  stats-db:
    image: postgres:14-alpine
    container_name: postgresql-stat
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistics-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  ewm-service:
    build: ./server
    container_name: explore-with-me-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore-with-me
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - statistics-server
      - STATISTICS-SERVER-URL=http://stats-server:9090
  ewm-db:
    image: postgres:14-alpine
    container_name: postgresql-explore-with-me
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore-with-me
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres




