

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(64) NOT NULL,

    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,

    CONSTRAINT uq_name UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat float,
    lon float

);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category BIGINT,
    confirmed_requests BIGINT,
    created_on timestamp WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR(7000) NOT NULL,
    event_date timestamp WITHOUT TIME ZONE NOT NULL,
    initiator BIGINT,
    location BIGINT,
    paid boolean NOT NULL DEFAULT FALSE,
    participant_limit BIGINT DEFAULT 0,
    published_on timestamp WITHOUT TIME ZONE,
    request_moderation boolean DEFAULT FALSE,
    state VARCHAR(64) NOT NULL,
    title VARCHAR(120) NOT NULL,
    comment_moderation boolean DEFAULT FALSE,

    CONSTRAINT fk_category FOREIGN KEY (category) REFERENCES categories(id),
    CONSTRAINT fk_initiator FOREIGN KEY (initiator) REFERENCES users(id),
    CONSTRAINT fk_location FOREIGN KEY (location) REFERENCES locations(id)

);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp WITHOUT TIME ZONE NOT NULL,
    event BIGINT,
    requester BIGINT,
    status VARCHAR,

    CONSTRAINT fk_event FOREIGN KEY(event) REFERENCES events(id),
    CONSTRAINT fk_requester FOREIGN KEY(requester) REFERENCES users(id),
    CONSTRAINT uq_event_of_user UNIQUE(event, requester)
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned boolean NOT NULL DEFAULT FALSE,
    title VARCHAR NOT NULL

);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT,
    events_id BIGINT,

    CONSTRAINT pk_comp_eve PRIMARY KEY (compilation_id, events_id),
    CONSTRAINT fk_copm FOREIGN KEY(compilation_id) REFERENCES compilations(id),
    CONSTRAINT fk_event FOREIGN KEY(events_id) REFERENCES events(id)

);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event BIGINT NOT NULL,
    owner BIGINT NOT NULL,
    text VARCHAR(7000) NOT NULL,
    status VARCHAR(64) NOT NULL,
    created_on timestamp WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_com_initiator FOREIGN KEY (owner) REFERENCES users(id),
    CONSTRAINT fk_com_event FOREIGN KEY (event) REFERENCES events(id)
)

